plugins {
    id "com.android.application"
}
android {
    namespace "com.blokmotor.oyun"
    compileSdk 34
    defaultConfig {
        applicationId "com.blokmotor.oyun"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }
}
